theme: jekyll-theme-cayman
titile: Rui Space
SEOTitle: Rui Space
# header-img: img/post-bg-rwd.jpg  	#显示在首页的背景图片
email: tclrg@126.com	
description: "一个无聊的网站"  			 #网站介绍
keyword: "" #关键词
url: "https://luanrui.me"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写
